### ISSUE TITLE
Linting broken in nextjs package

### ISSUE THREAD

**Issue by et** [highlight/highlight#4431]
```
cd e2e/nextjs/
yarn lint
```

Output:

```
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
node:internal/modules/cjs/loader:1075
  const err = new Error(`Cannot find module '${request}'`);
              ^

Error: Cannot find module '/Users/ericthomas/code/highlight/e2e/nextjs/node_modules/@highlight-run/next/dist/index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1075:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1068:15)
    at resolveExports (node:internal/modules/cjs/loader:551:14)
    at Module._findPath (node:internal/modules/cjs/loader:620:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:27)
    at mod._resolveFilename (/Users/ericthomas/code/highlight/e2e/nextjs/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:898:27)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/ericthomas/code/highlight/e2e/nextjs/next.config.js:1:33) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/ericthomas/code/highlight/e2e/nextjs/node_modules/@highlight-run/next/package.json'
}

Node.js v19.4.0
```

**Comment by et** [comment]
Fixed in #4428
