### ISSUE TITLE
go sdk panics when MarkBackendSetup is called without a session id

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4685]

**Comment by benmorehouse** [comment]
Hey @Vadman97 , gave this a brief look and it seems like a panic that would occur somewhere in this function: 

https://github.com/highlight/highlight/blob/main/sdk/highlight-go/highlight.go#L279

I was able to write a quick test for this part of the SDK and run it, and was able to replicate an error for that function. It's something specifically with how the Go GraphQL Client's Mutate function handles that map you give it.

Can you confirm that this is the expected problem that you found? If so, can whip up a quick change for this. Seems like a good first issue! 


```
(⎈ |AWS Prod | kubernetes | WRITE:applications)➜  highlight-go git:(main) ✗ go test
--- FAIL: TestMarkBackendSetup (0.00s)
    --- FAIL: TestMarkBackendSetup/should_throw_a_panic (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1361925]

goroutine 21 [running]:
testing.tRunner.func1.2({0x16030c0, 0x1b699d0})
        /usr/local/Cellar/go/1.19.5/libexec/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        /usr/local/Cellar/go/1.19.5/libexec/src/testing/testing.go:1399 +0x39f
panic({0x16030c0, 0x1b699d0})
        /usr/local/Cellar/go/1.19.5/libexec/src/runtime/panic.go:884 +0x212
github.com/hasura/go-graphql-client.(*Client).request(0x0, {0x17ae7f0, 0xc00003a140}, {0xc000120300?, 0x0?}, 0x0?, {0x1019d46?, 0x1bb55e0?, 0xc0001bce18?})
        /Users/benjamin/go/pkg/mod/github.com/hasura/go-graphql-client@v0.9.0/graphql.go:135 +0x225
github.com/hasura/go-graphql-client.(*Client).buildAndRequest(0x1?, {0x17ae7f0, 0xc00003a140}, 0x2d?, {0x15bdea0?, 0xc0003d4170?}, 0x100b287?, {0x0, 0x0, 0x0})
        /Users/benjamin/go/pkg/mod/github.com/hasura/go-graphql-client@v0.9.0/graphql.go:119 +0x278
github.com/hasura/go-graphql-client.(*Client).do(0x11?, {0x17ae7f0?, 0xc00003a140?}, 0xc6?, {0x15bdea0, 0xc0003d4170}, 0x732b8f7b?, {0x0, 0x0, 0x0})
        /Users/benjamin/go/pkg/mod/github.com/hasura/go-graphql-client@v0.9.0/graphql.go:246 +0x65
github.com/hasura/go-graphql-client.(*Client).Mutate(...)
        /Users/benjamin/go/pkg/mod/github.com/hasura/go-graphql-client@v0.9.0/graphql.go:66
github.com/highlight/highlight/sdk/highlight-go.MarkBackendSetup({0x17ae7f0, 0xc00003a140})
        /Users/benjamin/repositories/highlight/sdk/highlight-go/highlight.go:292 +0x2bb
github.com/highlight/highlight/sdk/highlight-go.TestMarkBackendSetup.func1(0x0?)
        /Users/benjamin/repositories/highlight/sdk/highlight-go/highlight_test.go:18 +0x27
testing.tRunner(0xc0000831e0, 0x16fb2a8)
        /usr/local/Cellar/go/1.19.5/libexec/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /usr/local/Cellar/go/1.19.5/libexec/src/testing/testing.go:1493 +0x35f
exit status 2
FAIL    github.com/highlight/highlight/sdk/highlight-go 0.645s
```

**Comment by Vadman97** [comment]
hey @benmorehouse , thanks for looking into this! so the bug for this customer in particular was that they had added the highlight `fiber` middleware without calling `H.Start()` causing the `client` object to be nil and that method to panic (see https://github.com/highlight/highlight/pull/4691). However there might still be another issue within the client if you can repro that panic after the change, so if you have a PR for that, that would be great to see.
