### ISSUE TITLE
[Nodejs/Nextjs] Cannot find module BatchSpanProcessorBase

### ISSUE THREAD

**Issue by AeShevch** [highlight/highlight#6741]
Greetings!

Wanted to use highlight-run/node, but it doesn't work.

I'm using nextjs, but I don't need the full integration - just to catch few console.logs on the backend.

So I just installed @highlight-run/node, and:

```js
import { H } from '@highlight-run/node';

H.init({ projectID: '***' });

...
console.log('my stuff');
```

Getting the error :
```
error - Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/node_modules/@opentelemetry/sdk-trace-base/build/src/export/BatchSpanProcessorBase' imported from /t/node_modules/@highlight-run/node/dist/index.mjs
Did you mean to import @opentelemetry/sdk-trace-base/build/src/export/BatchSpanProcessorBase.js?
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:330:11)
    at moduleResolve (node:internal/modules/esm/resolve:907:10)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

```

What am I doing wrong?

**To Reproduce**
1. npm install --save @highlight-run/node ("@highlight-run/node": "3.4.0",)
2. import { H } from '@highlight-run/node';
3. H.init({ projectID: '***' });
4. Getting the error

**Comment by Vadman97** [comment]
Thanks for the report @AeShevch ! This is likely related to recent changes form #6480 , will let @deltaepsilon look into this.

**Comment by AeShevch** [comment]
@Vadman97 Wow! I didn't expect such a lightning-fast response. Thank you, I look forward to it.

**Comment by deltaepsilon** [comment]
Definitely me.

Here's the PR that I hope will fix it:

https://github.com/highlight/highlight/pull/6712

That PR should land soon and close this issue. Upgrade `@highlight-run/node` and let me know how it goes!

**Comment by AeShevch** [comment]
@deltaepsilon, Hello!
Thanks for the fix!

But now I'm getting a new error:

```
error - Error: Dynamic require of "async_hooks" is not supported
    at node_modules/@highlight-run/node/dist/index.mjs:12:9
    at node_modules/@opentelemetry/context-async-hooks/build/src/AsyncHooksContextManager.js (node_modules/@highlight-run/node/dist/index.mjs:17388:22)
    at __require2 (node_modules/@highlight-run/node/dist/index.mjs:18:51)
    at node_modules/@opentelemetry/context-async-hooks/build/src/index.js (node_modules/@highlight-run/node/dist/index.mjs:17511:19)
    at __require2 (node_modules/@highlight-run/node/dist/index.mjs:18:51)
    at node_modules/@opentelemetry/sdk-trace-node/build/src/NodeTracerProvider.js (node_modules/@highlight-run/node/dist/index.mjs:24089:33)
    at __require2 (node_modules/@highlight-run/node/dist/index.mjs:18:51)
    at node_modules/@opentelemetry/sdk-trace-node/build/src/index.js (node_modules/@highlight-run/node/dist/index.mjs:24144:19)
    at __require2 (node_modules/@highlight-run/node/dist/index.mjs:18:51)
    at node_modules/@opentelemetry/sdk-node/build/src/index.js (node_modules/@highlight-run/node/dist/index.mjs:90905:21)
    at __require2 (node_modules/@highlight-run/node/dist/index.mjs:18:51)
    at node_modules/@highlight-run/node/dist/index.mjs:120160:31
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)

```

**Comment by AeShevch** [comment]
I've opened the new issue about this error – https://github.com/highlight/highlight/issues/6747

**Comment by deltaepsilon** [comment]
I'm going to close this in favor of #6747
