### ISSUE TITLE
Dynamic require of "async_hooks" is not supported

### ISSUE THREAD

**Issue by AeShevch** [highlight/highlight#6746]
I've made the issue yesterday about `BatchSpanProcessorBase` – https://github.com/highlight/highlight/issues/6741

@deltaepsilon made the fix, I updated to 3.4.1, and now I'm getting the new error:

```
error - Error: Dynamic require of "async_hooks" is not supported
    at node_modules/@highlight-run/node/dist/index.mjs:12:9
    at node_modules/@opentelemetry/context-async-hooks/build/src/AsyncHooksContextManager.js (node_modules/@highlight-run/node/dist/index.mjs:17388:22)
    at __require2 (node_modules/@highlight-run/node/dist/index.mjs:18:51)
    at node_modules/@opentelemetry/context-async-hooks/build/src/index.js (node_modules/@highlight-run/node/dist/index.mjs:17511:19)
    at __require2 (node_modules/@highlight-run/node/dist/index.mjs:18:51)
    at node_modules/@opentelemetry/sdk-trace-node/build/src/NodeTracerProvider.js (node_modules/@highlight-run/node/dist/index.mjs:24089:33)
    at __require2 (node_modules/@highlight-run/node/dist/index.mjs:18:51)
    at node_modules/@opentelemetry/sdk-trace-node/build/src/index.js (node_modules/@highlight-run/node/dist/index.mjs:24144:19)
    at __require2 (node_modules/@highlight-run/node/dist/index.mjs:18:51)
    at node_modules/@opentelemetry/sdk-node/build/src/index.js (node_modules/@highlight-run/node/dist/index.mjs:90905:21)
    at __require2 (node_modules/@highlight-run/node/dist/index.mjs:18:51)
    at node_modules/@highlight-run/node/dist/index.mjs:120160:31
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
```

To Reproduce

1. npm install --save @highlight-run/node ("@highlight-run/node": "3.4.0",)
2. import { H } from '@highlight-run/node';
3. H.init({ projectID: '***' });
4. Getting the error

**Comment by deltaepsilon** [comment]
@AeShevch Where are you running this code? Does it happen to be on Vercel? Is it Node.js or Edge?

I've seen this bug and fixed it before, but if you're still seeing it, I might be missing something.

**Comment by AeShevch** [comment]
@deltaepsilon I'm running this code locally in the nextjs Routes API (pages/api).

I don't use @highlight-run/next, only @highlight-run/node.

I did it this way because I don't need full integration with nextjs.
I just want to send logs like - request-response on several api routes.

**Comment by AeShevch** [comment]
I can't see the new version :(
<img width="516" alt="Screenshot 2023-10-05 at 20 12 53" src="https://github.com/highlight/highlight/assets/44289476/d66c1d4e-a328-460c-b62f-2422033e5d68">

**Comment by deltaepsilon** [comment]
> @deltaepsilon I can't see the new version :(
> 
> <img width="516" alt="Screenshot 2023-10-05 at 20 12 53" src="https://github.com/highlight/highlight/assets/44289476/d66c1d4e-a328-460c-b62f-2422033e5d68">
> 
Yesterday we released a new version of @highlight-run/next. I'm not certain if it bumped @highlight-run/node, but I'd recommend using the exports from @highlight-run/next instead. They're almost identical, but I put a lot of effort into making sure that they work on Vercel.

**Comment by deltaepsilon** [comment]
I believe that this was fixed some time ago. Closing.
