### ISSUE TITLE
RangeError: Maximum call stack size exceeded when logging Twilio Verification object

### ISSUE THREAD

**Issue by adymo** [highlight/highlight#6839]
**Describe the bug**

If Highlight is initialized, then the following code
```
  const verification = await twilio(sid, auth).verify.v2.services(verifySid).
    verifications.create({to: "<phone>",channel: 'sms'});
  console.log(verification);
```
fails to capture `console.log(verification)` output with 
```
~/projects/twilio_highlight_test/node_modules/@highlight-run/node/dist/index.js:120195
  function replacer(input) {
                   ^

RangeError: Maximum call stack size exceeded
    at replacer (~/projects/twilio_highlight_test/node_modules/@highlight-run/node/dist/index.js:120195:20)
    at replacer (~/projects/twilio_highlight_test/node_modules/@highlight-run/node/dist/index.js:120199:11)
    at replacer (~/projects/twilio_highlight_test/node_modules/@highlight-run/node/dist/index.js:120199:11)
...
```

**To Reproduce**
Here's the sample project you can use to reproduce the bug. You do need Twilio and Twilio Verify credentials to make it work.
[twilio_highlight_test.tar.gz](https://github.com/highlight/highlight/files/12861004/twilio_highlight_test.tar.gz)

**Expected behavior**
Twilio Verification object isn't that large to exhaust the stack size, so I wouldn't expect this to happen.

Here's a sample console.log output:
```
{
  sid: 'AAABBBAAABBBAAABBBAAABBB0123456789',
  serviceSid: 'AAABBBAAABBBAAABBBAAABBB0123456789',
  accountSid: 'AAABBBAAABBBAAABBBAAABBB0123456789',
  to: '+16500000000',
  channel: 'sms',
  status: 'pending',
  valid: false,
  lookup: { carrier: null },
  amount: null,
  payee: null,
  sendCodeAttempts: [
    {
      attempt_sid: 'AAABBBAAABBBAAABBBAAABBB0123456789',
      channel: 'sms',
      time: '2023-10-10T18:57:40.000Z'
    },
    {
      attempt_sid: 'AAABBBAAABBBAAABBBAAABBB0123456789',
      channel: 'sms',
      time: '2023-10-10T18:58:05.000Z'
    },
    {
      attempt_sid: 'AAABBBAAABBBAAABBBAAABBB0123456789',
      channel: 'sms',
      time: '2023-10-10T18:59:59.000Z'
    }
  ],
  dateCreated: 2023-10-10T18:57:40.000Z,
  dateUpdated: 2023-10-10T18:59:59.000Z,
  sna: undefined,
  url: 'https://verify.twilio.com/v2/Services/AAABBBAAABBBAAABBBAAABBB0123456789/Verifications/AAABBBAAABBBAAABBBAAABBB0123456789'
}
```

**Comment by Vadman97** [comment]
@adymo the fix to this is now released as @highlight-run/node v3.5.2 - let us know when you give it a try!
