### ISSUE TITLE
Max call stack exceeded trying to build flame graph

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#7377]
> seeing some crashes playing back sessions [https://app.highlight.io/1/sessions/KpWqmSNaAZdTHKFHfrAJXesFY04c?network-resource-id=\[…\]%2C2023-11-20T06%3A04%3A11.612Z_2023-12-20T06%3A04%3A11.612Z](https://app.highlight.io/1/sessions/KpWqmSNaAZdTHKFHfrAJXesFY04c?network-resource-id=12&page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-11-20T06%3A04%3A11.612Z_2023-12-20T06%3A04%3A11.612Z)

```
RangeError: Maximum call stack size exceeded
    at lA (utils.ts:110:29)
    at lA (utils.ts:124:3)
    at lA (utils.ts:124:3)
    at lA (utils.ts:124:3)
    at lA (utils.ts:124:3)
    at lA (utils.ts:124:3)
    at lA (utils.ts:124:3)
    at lA (utils.ts:124:3)
    at lA (utils.ts:124:3)
    at lA (utils.ts:124:3)
```

Context from Slack: [https://highlightcorp.slack.com/archives/C02N2AZS8BV/p1703052363382899](https://highlightcorp.slack.com/archives/C02N2AZS8BV/p1703052363382899)

```[tasklist]
### Tasks
- [ ] Don't return duplicate records from Clickhouse
- [ ] Avoid storing duplicate records in Clickhouse
```

**Comment by ccschmitz** [comment]
One of the issues we're running into here is that we have a lot of duplicate records for spans in our DB so we're returning a bloated number of spans.

![Image](https://github.com/highlight/highlight/assets/308182/d9b2cf84-5edd-447f-9277-48383c610c17)

In the linked network request that is being inspected, you can see that there are almost 3000 spans returned for the trace, and it seems like around 3/4 of them are from duplicates. This results in tons of overlapping spans which would cause the recursive logic to be triggered a lot than normal for span organization.

We should still look at ways to make the logic more efficient, but I have a hunch that this particular trace would work fine if we didn't have all the duplicate spans.

**Comment by ccschmitz** [comment]
Also wondering if this could be related to #7366 - another instance where we seem to be storing duplicates when ingesting data into Clickhouse.
