### ISSUE TITLE
Starting from v0.6.6, highlight_io masks FastAPI errors as 500 errors due to "Stream consumed"

### ISSUE THREAD

**Issue by huyouare** [highlight/highlight#7403]
**Describe the bug**
highlight_io is causing non-500 errors to generate 500 errors due to `Stream consumed` errors in starlette. AFAICT the starlette version does not change as a strict requirement between 0.6.5 and 0.6.6.

**To Reproduce**

1. Use highlight_io with Python FastAPI. Instrument code with ` app.add_middleware(FastAPIMiddleware)` (removing this line fixes the bug as well)
2. Start the FastAPI server, and call an endpoint that throws an error.
3. Observe that all errors are now 500 errors, due to "Stream consumed".

**Expected behavior**
Errors should be returned as expected, which happens in versions 0.6.5 and below.

**Additional context**
Example stack trace:

```
INFO: 127.0.0.1:59115 - "POST /v1/testset/ HTTP/1.1" 500 Internal Server Error
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app( # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/highlight_io/integrations/fastapi.py", line 41, in dispatch
    "http.request.detail": await request.body(),
                           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/requests.py", line 235, in body
    async for chunk in self.stream():
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/requests.py", line 218, in stream
    raise RuntimeError("Stream consumed")
RuntimeError: Stream consumed
INFO: 127.0.0.1:59314 - "POST /v1/run/ HTTP/1.1" 500 Internal Server Error
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app( # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/highlight_io/integrations/fastapi.py", line 41, in dispatch
    "http.request.detail": await request.body(),
                           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/requests.py", line 235, in body
    async for chunk in self.stream():
  File "/Users/jessehu/code/scorecard-backend/.venv/lib/python3.11/site-packages/starlette/requests.py", line 218, in stream
    raise RuntimeError("Stream consumed")
RuntimeError: Stream consumed
```

**Comment by Vadman97** [comment]
new SDK version with the fix is now released: https://pypi.org/project/highlight-io/0.6.10/
