### ISSUE TITLE
@highlight-run/nest v3.5.0 - TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.

### ISSUE THREAD

**Issue by rhefner** [highlight/highlight#8246]
Attempting to use `@highlight-run/nest@3.5.0` throws on our Nest API route:
```
[Nest] 98404   - 04/12/2024, 12:51:53 PM   [catch] You provided an invalid object where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.
TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.
    at Object.createInvalidObservableTypeError (<project>/node_modules/rxjs/src/internal/util/throwUnobservableError.ts:7:10)
    at Object.innerFrom (<project>/node_modules/rxjs/src/internal/observable/innerFrom.ts:41:9)
    at doInnerSub (<project>/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:5)
    at outerNext (<project>/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (<project>/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (<project>/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at <project>/node_modules/rxjs/src/internal/observable/innerFrom.ts:90:24
```

Downgrading to `3.4.0` doesn't have this issue.

Nest package versions we are using:
```
    "@nestjs/axios": "3.0.0",
    "@nestjs/cli": "10.1.18",
    "@nestjs/common": "10.2.7",
    "@nestjs/core": "10.2.7",
    "@nestjs/microservices": "10.2.7",
    "@nestjs/platform-express": "10.2.7",
    "@nestjs/platform-socket.io": "10.2.7",
    "@nestjs/serve-static": "4.0.0",
    "@nestjs/websockets": "10.2.7",
```

cc @Vadman97

**Comment by Vadman97** [comment]
wow thank you @rhefner , i didn't have a stack trace yet to dig into this (just had someone note a generic issue on discord). will get a fix out shortly

**Comment by Vadman97** [comment]
fixed is shipped in https://www.npmjs.com/package/@highlight-run/nest/v/3.6.0
