### ISSUE TITLE
unhandledRejection Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by MathiasGruber** [highlight/highlight#8300]
**Describe the bug**
ESM error when bumping to `7.4.10`

**To Reproduce**

* Upgrade `@highlight-run/next` from `7.4.8` to `7.4.10`
* Build application

**Expected behavior**
A successful build

**Additional context**
My entire codebase can be viewed here: [https://github.com/MathiasGruber/TheNinjaRPG](https://github.com/MathiasGruber/TheNinjaRPG)

```bash
vscode ➜ /workspace (main ✗) $ make pnpm build
Run pnpm
docker exec -it tnr_app pnpm build
 
> tnr@0.1.0 build /workspace/app
> next build
 
  ▲ Next.js 14.2.0
  - Environments: .env
  - Experiments (use with caution):
    · esmExternals
 
 ✓ Linting and checking validity of types
   Creating an optimized production build ...
 
unhandledRejection Error [ERR_REQUIRE_ESM]: require() of ES Module /workspace/app/node_modules/.pnpm/highlight.run@8.11.0/node_modules/highlight.run/dist/index.js from /workspace/app/node_modules/.pnpm/@highlight-run+next@7.4.10_@opentelemetry+api@1.8.0_next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/@highlight-run/next/dist/next-client.cjs not supported.
Instead change the require of index.js in /workspace/app/node_modules/.pnpm/@highlight-run+next@7.4.10_@opentelemetry+api@1.8.0_next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/@highlight-run/next/dist/next-client.cjs to a dynamic import() which is available in all CommonJS modules.
    at mod.require (/workspace/app/node_modules/.pnpm/next@14.2.0_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at Object. (/workspace/app/node_modules/.pnpm/@highlight-run+next@7.4.10_@opentelemetry+api@1.8.0_next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/@highlight-run/next/dist/next-client.cjs:2:39)
    at mod.require (/workspace/app/node_modules/.pnpm/next@14.2.0_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at 68803 (/workspace/app/.next/server/pages/_app.js:1:129)
    at o (/workspace/app/.next/server/webpack-runtime.js:1:127)
    at /workspace/app/.next/server/chunks/497.js:1:64360
    at o.a (/workspace/app/.next/server/webpack-runtime.js:1:866)
    at 10497 (/workspace/app/.next/server/chunks/497.js:1:64271)
    at o (/workspace/app/.next/server/webpack-runtime.js:1:127)
    at t (/workspace/app/.next/server/pages/_app.js:1:1749)
    at /workspace/app/.next/server/pages/_app.js:1:1786
    at o.X (/workspace/app/.next/server/webpack-runtime.js:1:1678)
    at /workspace/app/.next/server/pages/_app.js:1:1762
    at Object. (/workspace/app/.next/server/pages/_app.js:1:1814)
    at mod.require (/workspace/app/node_modules/.pnpm/next@14.2.0_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at requirePage (/workspace/app/node_modules/.pnpm/next@14.2.0_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js:109:84)
    at /workspace/app/node_modules/.pnpm/next@14.2.0_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:73:65
    at async Promise.all (index 1)
    at async loadComponentsImpl (/workspace/app/node_modules/.pnpm/next@14.2.0_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:71:33)
    at async Object.hasCustomGetInitialProps (/workspace/app/node_modules/.pnpm/next@14.2.0_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1273:24) {
  type: 'Error',
  code: 'ERR_REQUIRE_ESM'
}
   Collecting page data . ELIFECYCLE  Command failed with exit code 1.
make: *** [Makefile:58: pnpm] Error 1```
```

**Comment by MathiasGruber** [comment]
I'm still experiencing this in version 7.5.2
